# Run the full GLLAMMR cross-package validation suite and write RESULTS.md.
# Usage: Rscript validation/run_validation.R
# (validation/ is .Rbuildignore'd; this is a development artifact.)

library(GLLAMMR)

set.seed(2026)
res <- gllammr_validate(verbose = TRUE)

fmt <- function(x, digits = 4) ifelse(is.na(x), "NA", formatC(x, digits = digits, format = "g"))

lines <- c(
  "# GLLAMMR Validation Results",
  "",
  paste0("Generated by `validation/run_validation.R` on ", format(Sys.Date()), "."),
  "",
  paste0("R ", getRversion(), ", GLLAMMR ", as.character(utils::packageVersion("GLLAMMR")),
         ", TMB ", as.character(utils::packageVersion("TMB"))),
  "",
  "Reference packages using the same Laplace approximation (lme4 nAGQ=1,",
  "ordinal::clmm) agree to numerical precision; packages using different",
  "integration (mirt, ltm) agree within stated tolerances.",
  "",
  paste0("**Overall: ", sum(res$pass), " / ", nrow(res), " checks pass.**"),
  "",
  "| Case | Statistic | GLLAMMR | Reference | Rel. diff | Tolerance | Pass |",
  "|---|---|---|---|---|---|---|"
)

for (i in seq_len(nrow(res))) {
  lines <- c(lines, paste0(
    "| ", res$case[i],
    " | ", res$statistic[i],
    " | ", fmt(res$gllammr[i]),
    " | ", fmt(res$reference[i]),
    " | ", fmt(res$rel_diff[i], 3),
    " | ", fmt(res$tolerance[i], 3),
    " | ", ifelse(res$pass[i], "yes", "**NO**"),
    " |"))
}

lines <- c(lines, "",
  "## Known limitations",
  "",
  "- 2PL/3PL discrimination on very short tests (~5 items) can diverge under",
  "  the Laplace approximation (shared with joint ML); use longer tests or",
  "  wait for the adaptive quadrature option. Validated against mirt on a",
  "  20-item simulated test instead (correlations > 0.995).",
  "")

writeLines(lines, "validation/RESULTS.md")
cat("\nWrote validation/RESULTS.md -", sum(res$pass), "/", nrow(res), "checks pass\n")
